### PR TITLE
Initial Migration test from old marshaller to new one.

### PR DESCRIPTION
**Pull request by hasys**
Warning:
BPMN_EMBEDDED_SUBPROCESS file parsed incorrectly by new marshaller (lost some elements), so moved to separate method for now.

screenshot from 2018-01-25 19-12-33

It is initial commit. It checks only existing diagrams, I am done for today, tomorrow will add more complex examples.

P.S. don't forget to recompile: `kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common` module

### CODE REVIEW

**Comment by evacchi** [comment]
shall I wait for more commits or can I merge already? Thanks!

**Comment by hasys** [comment]
Hi @evacchi you can merge it. You can look at the found issue, if have a time, I will send new PR when will be ready.

**Comment by evacchi** [comment]
so, the reason why comparing Graphs does not work in the first place is that UUIDs do not match:

- it is true that my own marshaller is picking up the ID from a field of the XML (Process#id)
- it looks like the old marshaller's UUID does not occur in the original XML, which makes me think is being generated at runtime, rendering a simple equals (in this case) ineffective

If I fix the node ordering (they are being created in a different order from the old marshallers) or we use a set for comparison, then the first test passes! (We should probably check edges as well, though)

**Comment by evacchi** [comment]
see https://github.com/kiegroup/kie-wb-common/pull/1390

EDIT: there is an additional issue. Parent/child relationship edges have UUIDs but these are generated dynamically. We can't really compare them to each other unless we ignore UUIDs here. I believe it might make sense, here, since the ID in this case does imply *identification* but not *equality*; i.e., two (relationship) edges (a,b), (x,y) are equal iff a=x, b=y, the ID would not play a role here. Different case for SequenceFlows, because the ID is part of the BPMN definition, so in this case it would make sense to compare IDs.

**Pull request merged**
